services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Madj2k\GadgetoGoogle\:
    resource: '../Classes/*'

  Madj2k\GadgetoGoogle\Service\Geolocation:
    public: true

  Madj2k\GadgetoGoogle\Service\GeolocationService:
    public: true

  Madj2k\GadgetoGoogle\Controller\AdminModuleController:
    tags: ['backend.controller']

  cache.gadgetogoogle_filteroptions:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: [ '@TYPO3\CMS\Core\Cache\CacheManager', 'getCache' ]
    arguments: [ 'gadgetogoogle_filteroptions' ]

  Madj2k\GadgetoGoogle\Controller\MapController:
    calls:
      - method: 'injectCache'
        arguments:
          $cache: '@cache.gadgetogoogle_filteroptions'

  cache.gadgetogoogle_navigationobjects:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: [ '@TYPO3\CMS\Core\Cache\CacheManager', 'getCache' ]
    arguments: [ 'gadgetogoogle_navigationobjects' ]

  Madj2k\GadgetoGoogle\Controller\LocationController:
    calls:
      - method: 'injectCache'
        arguments:
          $cache: '@cache.gadgetogoogle_navigationobjects'
